apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: flask-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-dep
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

