apiVersion: v1
kind: Service
metadata:
  name: svc-app
spec:
  selector:
    app: my-dep
  ports:
  - protocol: TCP
    port: 80        # Port exposed by the Service
    targetPort: 5000 
    nodePort: 30000 
  type: NodePort
